---
title: Westwood Robotics
timezone: America/New_York
collections:
  '2017':
    title: '2017'
    output: true
  '2018':
    title: '2018'
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@whsrobotics.org
website: https://whsrobotics.org
author: Westwood Robotics
description: Follow Westwood Robotics' latest updates! Westwood Robotics specializes
  in STEM and robotics education for all children.
baseurl: 
url: https://blog.whsrobotics.org
instagram_username: wwrobotics1757
twitter_username: wwrobotics1757
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
show_excerpts: true
