---
title: Westwood Robotics Blog
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@whsrobotics.org
author: Westwood Robotics
description: Follow Westwood Robotics' latest updates! Westwood Robotics specializes
  in STEM and robotics education for all children.
baseurl: ''
url: https://blog.whsrobotics.org
instagram_username: wwrobotics1757
twitter_username: wwrobotics1757
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
